name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "Hello World!"
      - name: test
        run: echo "test build"
      - name: deploy
        run: echo "deploying app"
